config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "rooms#index"
  resources :users, only: [:edit,:update]
  resources :rooms, only: [:new, :create, :destroy] do
    resources :messages, only: [:index, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :room
  belongs_to :user
  has_one_attached :image
  #「has_one_attached」で、各レコードと画像ファイルを1対1の関係で紐づけることができる。

  validates :content, presence: true, unless: :was_attached?

  def was_attached?
    self.image.attached?    # テキストが存在していなくても画像の投稿を可能にする。
  end
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :room_users
  has_many :users, through: :room_users, dependent: :destroy
  has_many :messages, dependent: :destroy
  # 「dependent: :destroyオプション」とは、親モデルが削除された時、それに紐付ている子モデルも一緒に削除されるというオプション。
  #ここで注意なのが、あくまでも「チャットルームに紐づいているユーザー情報を削除」なので、「メンバーの削除＝中間テーブルから該当するレコード削除」ということになる。
  #つまり一度登録したユーザー情報はusersテーブルに残ったまま。

  validates :name, presence: true 
end

app/models/room_user.rb
class RoomUser < ApplicationRecord
  belongs_to :user
  belongs_to :room
  #中間テーブルにuser_id,room_idに空で登録出来ないようにするバリデーションは付けなくていい
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :room_users
  has_many :rooms, through: :room_users
  has_many :messages

  validates :name, presence: true       #空で登録できないようバリデーションを設定
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?    #nicknameカラムの保存を可能にする。
                                                                            #Railsでは、悪意のあるユーザーの入力に対してセキュリティ対策を行わないと保存できない仕組みがあるので、devise_parameter_sanitizerメソッドを使用し特定のカラムを許容する。
  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  
  def index
    @message = Message.new
    @room = Room.find(params[:room_id])
    @messages = @room.messages.includes(:user)
     # チャットルームに紐付いている全てのメッセージ : @room.messages
     #全てのメッセージ情報に紐づくユーザー情報を、includes(:user)と記述をすることにより、ユーザー情報を1度のアクセスでまとめて取得することができる。
  end

  def create   #メッセージフォームから投稿した際にこのアクションを実行
    @room = Room.find(params[:room_id])
    @message = @room.messages.new(message_params)
    if @message.save
      redirect_to room_messages_path(@room)
    else
      render :index
    end
  end

 



  private

  def message_params
    params.require(:message).permit(:content, :image).merge(user_id: current_user.id)
  end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  
  def index
  end

  
  def new
    @room = Room.new
  end

  def create
    @room = Room.new(room_params)       #Railsでは、保存する前に必ずストロングパラメーターを使って許可を行わなければ、データの保存がされないように、セキュリティ対策が取られている、
    if @room.save
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    room = Room.find(params[:id])
    room.destroy
    redirect_to root_path
  end

  private

  def room_params
    params.require(:room).permit(:name, user_ids: [])     #配列に対して保存を許可したい場合は、キーの名称と関連づけてバリューに[]と記述。
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit
  end

  def update
    current_user.update(user_params)      #編集内容が更新されるように、コントローラーを編集
    if current_user.update(user_params)   #ユーザー情報の更新に成功した場合、チャット画面に遷移するように実装
      redirect_to root_path
    else
      render :edit      #更新に失敗するとeditページに戻ってくるよう実装
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChatApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css">      
    <%# Yahoo!が開発した「YUI 3」というリセットCSSを使用。(url先に指定) %>
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/_main_chat.html.erb
<div class = "chat_header" >
  <div class="left-header">
    <div class = "chat_room_name">
      <%= @room.name %>
    </div>
  </div>
  <div class="right-header">
    <div class = "chat_end">
      <%= link_to "チャットを終了する", room_path(@room), method: :delete %>
    </div>
  </div>
</div>
 <div class="messages" >
    <%= render partial: 'message', collection: @messages %>
</div>
<%= form_with model: [@room, @message], html: {class: "form"}, local: true do |f|%>
  <div class="form-input">
    <%= f.text_field :content, class: 'form-message', placeholder: 'type a message' %>
    <label class="form-image">
      <span class="image-file">画像</span>
      <%= f.file_field :image, class: 'hidden' %>
    </label>
  </div>
  <%= f.submit '送信', class: 'form-submit' %>
<% end %>

app/views/messages/_message.html.erb
<div class="message">
  <div class="upper-message">
    <div class="message-user">
    <!-- 投稿したユーザー名情報を出力する -->
      <%= message.user.name %>       <%# messagesテーブルのuser_idに紐付いているユーザー名を、user.nameと記述することで取得。 %>
    </div>
    <div class="message-date">
      <!-- 投稿した時刻を出力する -->
      <%= l message.created_at %>     <%# l（エル）メソッドは日付や時刻を表示するメソッド。国や地域によって時刻は異なるが、lメソッドを使えば指定した現地時間に対応できる。 %>
    </div>
  </div>
  <div class="lower-message">
    <div class="message-content">
    <!-- 投稿したメッセージ内容を記述する -->
      <%= message.content %>
    </div>
    <%= image_tag message.image.variant(resize:'500x500'), class: 'message-image' if message.image.attached?%>
    <%# 「 image_tag message.image, class: 'message-image' 」で「画像の投稿」と「投稿した画像の表示」が可能となる。  %>
    <%# 「それ以降の記述で、画像が存在する場合のみimage_tagが読み込まれるようになる  %>
    <%# variantメソッド(「variant(resize:'500×500')」)はActive Storageを導入している場合に使用可能だが、ビュー側で使用したサイズをその都度指定できる。 %>
    <%# 「x」は英字のx(エックス)の小文字 %>
  </div>
</div>

app/views/messages/_side_bar.html.erb
<div class = "side_bar_header" >
  <div class = "top_name">
    <%= link_to edit_user_path(current_user) do %>    <%# サイドバーからユーザー編集ページに遷移できるように、ビューファイルを編集 %>
      <%= current_user.name %>                        <%# 表示されているユーザー名をログイン中のユーザー名にする %>
    <% end %>
  </div>
  <div class = "create_chat">
    <%# <a href = 'rooms/new' >チャットを作成する</a> %>  <%# →これでもOK! %>
    <%= link_to "チャットを作成する", new_room_path %>
  </div>
</div>
<div class = "rooms" >
  <div class = "room">
  <%# サイドバー下部への新規作成したチャットルーム名の表示を実装 %>
    <% current_user.rooms.each do |room|%>  
      <div class="room">
        <div class="room_name">
          <%= link_to room.name, room_messages_path(room) %>    <%# パスにroomを引数とすることで、メッセージと紐付いているチャットルームのidを持たせることができる。これしないとエラー出る。 %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/messages/index.html.erb
<div class="wrapper" >
  <div class ="side_bar">
    <%= render "side_bar" %>

  </div>
  <div class ="chat">
    <%= render "main_chat" %>
  </div>
</div>

app/views/rooms/index.html.erb
<div class="wrapper" >
  <div class ="side_bar">
    <%= render "messages/side_bar" %>   <%# 「messages」フォルダの「_side_bar.html.erb」から部分テンプレートを読み込み %>
  </div>
</div>

app/views/rooms/new.html.erb
<div class='chat-room-form'>
  <h1>新規チャットルーム</h1>
  <%=form_with model: @room, local: true do |f|%>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'>
        <%= f.label :チャットルーム名, class: 'chat-room-form__label'%>
      </div>
      <div class='chat-room-form__field--right'>
        <%= f.text_field :name, class: 'chat__room_name chat-room-form__input', placeholder: 'チャットルーム名を入力してください'%>
      </div>
    </div>
    <div class='chat-room-form__field'>
    </div>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'>
        <label class='chat-room-form__label' for='chat_room_チャットメンバー'>チャットメンバー</label>
      </div>
      <div class='chat-room-form__field--right'>  
        <select name="room[user_ids][]">
          <option value="">チャットするユーザーを選択してください</option>
          <% User.all.where.not(id: current_user.id).each do |user|%>     <%# 「.where.not(id: current_user.id)」で現在ログイン中のユーザー名を選択リストから除外 %>
            <option value=<%=user.id%>><%= user.name %></option>
            <%# select要素のname属性にroom[user_ids][]を指定し、option要素のvalue属性にuser.idを指定。このように記述することで、room[user_ids][]をキーに「user.id」をparamsでコントローラー側へ送信できる。 %>
          <% end %>
        </select>
        <input name="room[user_ids][]" type="hidden" value=<%=current_user.id%>>    <%# paramsでコントローラーに送信する情報にカレントユーザーのidも含める。 %>
      </div>
    </div>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'></div>
      <div class='chat-room-form__field--right'>
        <%= f.submit class: 'chat-room-form__action-btn'%>
      </div>
    </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class='account-page' id='account-page'>
  <div class='account-page__inner clearfix'>
    <div class='account-page__inner--left account-page__header'>
      <h2>Edit Account</h2>
      <h5>アカウントの編集</h5>
      <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'%>
      <%= link_to "チャットページに戻る", :back, class: 'btn'%>
    </div>
    <div class='account-page__inner--right user-form'>
      <%= form_with model: current_user, local: true do |f|%>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :name%>
          </div>
          <div class='field-input'>
            <%= f.text_field :name, autofocus: true%>
          </div>
        </div>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :email%>
          </div>
          <div class='field-input'>
            <%= f.email_field :email%>
          </div>
        </div>
        <div class='actions'>
          <%= f.submit "Update", class: 'btn'%>
        </div>
      <% end %>
    </div>
  </div>
</div>